### ISSUE TITLE
No editing menu

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#1]
When I bring up [https://saktumiva.org/wiki/rasendramangala/london_l.](https://saktumiva.org/wiki/rasendramangala/london_l), I don't see the menu on the right for editing the header (and whole file).

![Screenshot from 2019-10-29 19-10-17](https://user-images.githubusercontent.com/762246/67820665-ce461200-fa7f-11e9-9c03-b35a532729f6.png)

**Comment by chchch** [comment]
Fixed!
