### ISSUE TITLE
lemmatization fail?

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#11]
At [Rasendramangala Kaksaputa ](https://saktumiva.org/wiki/wujastyk/rasendramangala/chapter4-srisaila/provisional_edition#?upama_ver=gfvzyn7fgz)verse 87cd, I am wondering why Saktumiva isn't aligning _narasya_ with _rasasya_ etc.?

![image](https://user-images.githubusercontent.com/762246/128055088-440cce54-967b-4056-9915-ce1042452c59.png)

Here's the overview:

![image](https://user-images.githubusercontent.com/762246/128055277-f99e3ada-39bc-4a91-b97d-eb367e1a1dff.png)

**Comment by chchch** [comment]
Hmm, that makes sense to me. The "na" in "narasya" seems to align with the "ni" in "krameṇaitāni". I think this is a case where I would take "krameṇaitāni śasya" as one lemma. If you get a chance, try helayo in akṣara mode, and then use the "group words" function to get nicer lemmata: https://chchch.github.io/sanskrit-alignment/docs/

**Comment by wujastyk** [comment]
okay!  I haven't used helayo yet, and it's time I did.  Thank you, Charles.

The narasya/rasasya branch is probably wrong, because it doesn't scan.
This line baffles me.
