### ISSUE TITLE
Slightly puzzling display involving <add>

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#18]
One source MS says:
```
 <l xml:id="SS.5.1.52">sphoṭājanmarujāsrāvas tvakpākaḥ sveda<unclear>m
                            e</unclear>va ca |<cb/>
                        <caesura/>
                         dāraṇañ cāpi māṃsānām abhyaṅge viṣadūṣite |</l>
```

The collated edition says:

![image](https://user-images.githubusercontent.com/762246/133686272-d0706345-516f-4292-ba3a-17fb0af58e9d.png)

What has happened to that unclear "e" of eva ca in witness K?

**Comment by chchch** [comment]
Hmm, I think this is because `<unclear>` is set to "ignore tags only", and so `<unclear>e</unclear>va` doesn't show up as a variant for `eva`.

**Comment by wujastyk** [comment]
That sounds likely.  I realize now that I don't properly understand
hide/ignore all/ignore tags only/include.  The documentation
<https://saktumiva.org/wiki/users> says "ignores the tag but keeps the text
inside the tag for comparison".  Wouldn't that mean the "e" ... oh, no, I
see.   Thank you!

**Comment by chchch** [comment]
I struggled with the semantics of the names of the options, and I settled on "ignore all" and "ignore tags only". But if you have any thoughts on that let me know!

**Comment by wujastyk** [comment]
for me, the answer was rtfm.  :-)
