### ISSUE TITLE
non-validating XML in Saktumiva transcriptions

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#19]
To get the neat notes to the apparatus, I use the `<div2>` syntax.  E.g.,
![image](https://user-images.githubusercontent.com/762246/134994563-197a9c9a-4e9b-4479-9845-822a75eb7cb4.png)

But as this shows, my TEI validator doesn't recognize `<div2>` or this use of `@target`.  This doesn't matter except for one thing.  I have enough of these structures that the parser always generates many parsing error messages that obscure the "real" errors that I actually need to fix.

Can we either update the syntax to be TEI-conformant, or create a Saktumiva schema?  I'd rather not create a new schema because it just adds to an already adequately complex system. :-)

**Comment by chchch** [comment]
Hmm, for the apparatus, how about `<standOff>` with `@corresp`? So something like

`<standOff type="apparatus" xml:id="SS.1.1.30-app" corresp="#SS.1.1.30">`

`<nex:nexml>` has its own namespace, so that should be ok... `<xenoData>` is meant to contain non-TEI things. Maybe we can replace `<stemma>` with `<tree>`?

**Comment by wujastyk** [comment]
My parser spits out `standOff` too.  I don't see why.  (Also, the parser likes `@coresp` but not `@type`.)  I can't see yet, from the [Guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SASOstdf), why this isn't working in my document.  

Wait, I think `<standOff>` may be illegal inside `<text>`.

**Comment by chchch** [comment]
Ah ok, I see, so if we used `<standOff>` it would have to be outside the text block, like at the bottom or something. But it would be nicer to have the apparatus just below the text that it's referring to, right?

**Comment by wujastyk** [comment]
yes, it's easier to edit and think about stuff if it's all on the screen in
one place.

**Comment by wujastyk** [comment]
How about just `<ab>`.  The parser likes it.  I don't know if it's the True Meaning of `ab` but if if works....

```
<ab xml:id="SS.1.1.xxx" type="apparatus" corresp="#SS.1.1.20x">
    <list><item></item></list>
</ab>
```

**Comment by chchch** [comment]
Ok, I've just updated all the relevant files to accept `<ab>`. So it should look something like this:
```xml
<ab xml:id="SS.1.1.xxx" type="apparatus" corresp="#SS.1.1.20x">
    <list type="testimonia">
        <item corresp="#SS.1.1.20x-n1"></item>
    </list>
</ab>
```

The `@corresp` on the `<item>` points to an `<anchor>` in the text, e.g., `<anchor n="SS.1.1.20x-n1"/>` which is basically just a footnote marker. 

For `@type` on `<list>`, I've been using `sources`, `parallels`, and `testimonia`, which turns into 3 separate levels of apparati when you export to LaTeX. I guess we can add a fourth one, `notes`? The only thing is that I ran out of footnote markers when exporting to LaTeX; I'm using Western numerals, lowercase Roman numerals, and uppercase Roman numerals respectively, and I couldn't think of a fourth kind of numeral for notes.

**Comment by wujastyk** [comment]
So is it the case that the `@corresp` in the `<ab>` corresponds to the `xml:id` of the text (commonly `<l>`) in whose apparatus the note will sit?  

Does that mean the main `xml:id` of the `<ab>` isn't being used?

Also, is the `<anchor>` going to produce a superscript number in the main text?  I don't think we want that, do we?

--

As for note numbers, how about symbols?  Or Devanagari numerals?  Or each note could just get the list's bullet.  Do we need numbering?

**Comment by chchch** [comment]
I think the `@xml:id` on the `<ab>` element is used so that when you click on the asterisk that marks the note, it knows where to go. Maybe we could do without though... I'll check the code. 

The `<anchor>` just produces an asterisk in the online interface at the moment; the footnote numbering is specifically for LaTeX export, where we don't have a fancy clickable interface.

**Comment by wujastyk** [comment]
I'm getting a good result with this:

**Input**:
```
                    <l xml:id="SS.1.1.20x">bha |<anchor n= "SS.1.1.20x-n1"/></l>
                    
                    <ab xml:id="SS.1.1.20x-app" corresp="#SS.1.1.20x" type="apparatus">
                        <list type="notes">
                            <item corresp="#SS.1.1.20x-n1">The Nepalese witnesses use the abbreviation "bha" for "bhavati
                                cātra", introducing the next verse.</item>
                        </list>
                    </ab>
```

**Output**:
![image](https://user-images.githubusercontent.com/762246/135324089-bbab183d-fca8-45b5-b643-4cfe956731fd.png)

Clicking on the asterisk highlights the note (but not vice-versa). I see now that multiple notes may need multiple numbers when printed out via latex, but they're okay on screen without numbering, aren't they?

The `xml:id` of the `<ab>`, with the suffix `-app` is apparently not used.

**Comment by chchch** [comment]
Yeah, note numbering is just an issue for the printed text, I think. I'll add reverse highlighting.

**Comment by wujastyk** [comment]
Um, it makes my head swim a little, so I may be quite wrong.  But I think that this syntax isn't perfect because there are `@corresp` attributes without any `@target`.  It works fine in Saktumiva, but is it syntactically okay?  Should the `@corresp` in `<list>` perhaps be an `xml:id` or a `@target`?

```
  <ab xml:id="SS.1.16.3-app" corresp="#SS.1.16.3" type="apparatus">
                        <list type="testimonia" corresp="#SS.1.16.3-n1">
                            <item corresp="#SS.1.16.3-n1">
                            ...
```

**Comment by chchch** [comment]
I actually replaced `@target` with `@corresp` because it wasn't supported. You actually don't need `@corresp` on the `<list>` element, because the notes correspond to each `<item>`, not to the whole list.

**Comment by wujastyk** [comment]
Ah, I see. Thank you!
So, would I be right in thinking that the `-app` and `-n1` suffixes are meaningful for Saktumiva, but don't do any work within the TEI encoding?

**Comment by chchch** [comment]
In yhid:
```xml 
<item corresp="#SS.1.16.3-n1"> 
```
the "-n1" id is used to link that note to an `<anchor>` with the same id. I guess the `-app` id isn't needed, but I should check through the code.

**Comment by wujastyk** [comment]
Ah, of course, I'd forgotten about the `<anchor>`.  Thanks again, Charles.

**Comment by chchch** [comment]
I think we fixed this one!
