### ISSUE TITLE
Validating <xenoData> <stemma> etc.

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#21]
Moving this part of the #19 discussion here, to it's own thread.

`<tree>` for `<stemma>` doesn't help.  My parser seems to be saying that xenoData can only contain comments and character data, so `<stemma>` shouldn't be a problem.   That's odd.

![image](https://user-images.githubusercontent.com/762246/135326945-523dd4a8-8d47-43d7-bd69-d18f6c6fdd9f.png)

Looking at the [Guidelines on xenoData](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-xenoData.html), the above parser problem with `<stemma>` seems wrong. Shouldn't it accept anything at all? Am I missing something?

Putting all of xenoData's content into comments works okay:
```
  <xenoData><!--
            <stemma format="nexml">
                <nex:nexml generator="Bio::Phylo::Project v.0.58" version="0.9"
                    xmlns="http://www.nexml.org/2009" xmlns:dc="http://purl.org/dc/elements/1.1/"
                    xmlns:map="http://phylomap.org/terms.owl#" xmlns:nex="http://www.nexml.org/2009"
                    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.nexml.org/2009 http://www.nexml.org/2009/nexml.xsd"
                    > <otus id="otus1" label="TaxaBlock">
                        <otu id="otu1" label="A"/>
                        <otu id="otu2" label="H"/>
                        <otu id="otu3" label="K"/>
                        <otu id="otu4" label="N"/>
                    </otus> <trees otus="otus1" id="trees1" label="TreesBlock">
                        <tree id="tree1" label="tree1" xsi:type="nex:FloatTree">
                            <node id="n1" label="A" otu="A"/>
                            <node id="n2" label="H" otu="H"/>
                            <node id="n3" label="K" otu="K"/>
                            <node id="n4" label="N" otu="N"/>
                            <node id="n5" label="n5"/>
                            <node id="n6" label="n6"/>
                            <node id="n7" label="n7" root="true"/>
                            <edge source="n5" target="n2" id="e1" length="0.0016219388250720487"/>
                            <edge source="n5" target="n4" id="e2" length="0.0030085840381346013"/>
                            <edge source="n6" target="n1" id="e3" length="0.023868550299649984"/>
                            <edge source="n6" target="n5" id="e5" length="5.44043353790739E-4"/>
                            <edge source="n7" target="n6" id="e6" length="4.092575344587166E-5"/>
                            <edge source="n7" target="n3" id="e7" length="7.775893154715614E-4"/>
                        </tree> </trees>
                </nex:nexml>
            </stemma>
        -->
        </xenoData>
```

Would Saktumiva be able to extract what it needs from commented-out material?

PS:
But since fixing the `<div2>` issue with `<ab>`, I'm now only getting two parse errors in this file, from `<stemma>`, which is completely tolerable.  So we don't really need to fix this.

**Comment by chchch** [comment]
I guess `<xenoData>` is supposed to contain things that are_outside_ the TEI spec, so anything that isn't bound to a different namespace will result in an error. I guess there we would actually have to make a new namespace for `<stemma>`, and do something like `<upama:stemma>`. The only reason that I still have `<stemma>` is because I think there are still two types of tree formats supported: `<stemma format="nexml">` and `<stemma format="newick">`, although I haven't tried using a newick tree in a while.
