### ISSUE TITLE
problem with <ab>?

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#22]
The structure below worked fine in earlier tests, but now it stops my file displaying:

```
<l xml:id="SS.1.1.20x">bha |<anchor n= "SS.1.1.20x-n1"/></l>
                    
<ab xml:id="SS.1.1.20x-app" corresp="#SS.1.1.20x" type="apparatus">
  <list type="notes">
    <item corresp="#SS.1.1.20x-n1">The Nepalese witnesses use the 
      abbreviation "bha" for "bhavati cātra", introducing the next verse.
    </item>
  </list>
</ab>
```

**Comment by chchch** [comment]
Hmm, the file you've attached seems to work fine, sans `<ab>`.

I'm still trying to figure out the issue with `<ab>`... it seems to be a problem in the XSLT, which is a little difficult to debug.

**Comment by wujastyk** [comment]
`<ab>` is working well now.  Thank you!
