### ISSUE TITLE
Q: how to transcribe duplicate folia

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#30]
Deepro noted this situation:

> I have been working on Chapter 19 of the Cikitsāsthāna. The KL 699 contains certain parts of the text twice in two different folios in two different handwritings. In Andrey's images, the extra folios are named with an underscore (_) as in 112_rIMG_0142.JPG and the usual ones are without the underscore as in 112rIMG_0142.JPG. 

>My question is: when a certain part of the text occurs in both places, how should I keep that in my transcription?

**Comment by chchch** [comment]
I think I would actually treat them as two separate witnesses. It'll also keep things clearer when you want to do some phylogenetic/stemmatic anaylsis. In my _Prakīrṇaprakāśa_ manuscripts, I have one manuscript that contains two copies of the text, and I just transcribed them as two separate witnesses — then when I build a stemma, one of them shows up clearly as a (corrupted) copy of the other one.

**Comment by wujastyk** [comment]
Good.  That's what we'll do.
