### ISSUE TITLE
Sharada Separator

### ISSUE THREAD

**Issue by chakrabortydeepro** [chchch/upama#31]
@chchch Charles, is there any way to produce the Sharada separator (U+111C8)?
I can use a hyphen `-` but it would then need to be shown properly in the Sharada transliteration.  

Here is an example:
![image](https://user-images.githubusercontent.com/34675461/147212066-f6b827c0-6888-4943-b7ad-ec15989639c9.png)
I can do it as `hrasva-dīrgha-plutatvā--` 
or 
`hrasva<metamark function="separator">-</metamark>dīrgha<metamark function="separator">-</metamark>plutatvā<metamark function="separator">--</metamark>`
or
`hrasva<note type="separator">-</note>dīrgha<note type="separator">-</note>plutatvā<note type="separator">--</note>`
Please let me know what you think.

**Comment by chchch** [comment]
Hmm, I think I would encode this either as
```xml
<note place="below">|</note>
```
or
```xml
<add place="below">|</add>
```
Since these seem to be subscript daṇḍas, analogous to the sandhi marks discussed in issue #28.

**Comment by chakrabortydeepro** [comment]
All right, thanks, Charles.

**Comment by chakrabortydeepro** [comment]
@chchch Would it be possible to add a code for the Sharada separator as `<g ref="#sharada-separator"/>` . `<add place="below">|</add` does not really serve a purpose here. It's not an added character. It is not between clauses but between words. The display gets messy with so many unnecessary _daṇḍas_. Using the Unicode Character “𑇈” ([U+111C8](https://www.compart.com/en/unicode/U+111C8)) for the Sharada separator will serve my purpose way better and I can better distinguish it from an added _daṇḍa_ . Thanks!

**Comment by chchch** [comment]
Done! Let me know if it works and then we can close the issue. I also added it here: https://saktumiva.org/wiki/transcription

**Comment by chakrabortydeepro** [comment]
Looks perfect! Great!
![image](https://github.com/chchch/upama/assets/34675461/3d39c2eb-907e-4e1d-ad9b-e74878bb44be)
![image](https://github.com/chchch/upama/assets/34675461/9abfc4ef-6dac-4091-9cd3-643b81a6408f)

Thank you so much, Charles. I'm closing the issue.
