### ISSUE TITLE
Gemination after r, over a space

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#35]
Hi, Charles, we have a case like this:
![image](https://user-images.githubusercontent.com/762246/163228869-50192336-e081-4f2f-92f5-c50e3a430795.png)

"Gemination after r" is switched on, but it's not seeing _vvyavāyo_, presumably because of the space after _ahar_.  

Should the rule be modified to catch such cases?
Best,
Dominik

**Comment by chchch** [comment]
Hmm... isn't that the appropriate behaviour, to ignore _vvyavāyo_?

**Comment by wujastyk** [comment]
I thought I should see _vyavāyo_ (no gemination) in the apparatus, no?  I mean, rather, that _vvyāvāyo_ shouldn't appear in the apparatus at all, because it is only distinguished by the "gemination after r, and that should be filtered out.

**Comment by wujastyk** [comment]
Oh!  Silly me.  I was looking at the wrong part of the word.  Thank you, Charles!

**Comment by chchch** [comment]
👍👍 Sometimes I use `<sic>` in these cases so that I don't go cross-eyed trying to read it!
