### ISSUE TITLE
Documenting <pc> </pc>

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#37]
Could you document this element at the TEI tagging help page on Saktumiva?

- [https://saktumiva.org/wiki/tei](https://saktumiva.org/wiki/tei)

**Comment by chchch** [comment]
Done! I think. Do we use <pc> for anything else?

**Comment by wujastyk** [comment]
did something get lost in the previous sentence?  

PS, I found I could edit the TEI tagging page, so I added a sentence to `<pc>` to make it clear to users that they don't think they have to do this for all compounds.

**Comment by chchch** [comment]
Yes sure, thanks!
