### ISSUE TITLE
feature request: screen capture printout size

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#40]
Dear Charles,
I have a user who would like to have a printout from the Saktumiva screen to work with (ctrl+P). The font size of the printout is a bit small.  If you enlarge the script size on the screen, it makes no difference to the size of the printout.  

Is there a way to get a larger size of printout?  Or to get the printout to match the font size of an enlarged screen?

Thanks!
Dominik

**Comment by chchch** [comment]
Hmm... weird, on Firefox on Linux it gives me a "Scale" option; if I set it to "200" the font size goes mega big. Chrome also lets me do the same...

**Comment by wujastyk** [comment]
I'm Firefox on Linux too. Where are you seeing that option?  In the URL bar?  I see that too, but it makes no difference to the printout.  Or are you seeing it in a print dialogue?

**Comment by chchch** [comment]
I get it on the right hand side of the screen: 

![image](https://user-images.githubusercontent.com/1082192/171872624-9248d169-56c9-41b0-8466-007a5460d221.png)

**Comment by wujastyk** [comment]
aaaaah! It was hidden under a collapsed "more settings".  Duh.  I can't
work my own computer.   Thank you, Charles!  Yes, now I see the font
expands just as you said.
