### ISSUE TITLE
Commented out note is being displayed

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#44]
In the attached file, [hv-05-k-ocr.txt](https://github.com/chchch/upama/files/9802069/hv-05-k-ocr.txt), in line 209, we have an `<anchor>`, and after that a `<metamark>` and `<note>`, which, although being commented out, appears when [displayed](https://muk.li/upama/haravijaya:05:hv-05-k-ocr). Is this a bug, or are we doing something wrong here?

**Comment by chchch** [comment]
The anchor is pointing to `<ab type="apparatus" corresp="#HVVU_05_010">`, which has the corresponding note. If you want it not to be displayed, you should comment out the `<anchor>` as well as the `<ab>` I think.

**Comment by wujastyk** [comment]
It's good to have a fix.  But it's odd that Saktumiva can "see" strings that are commented out.  (If I have understood the situation correctly.)

**Comment by chchch** [comment]
In this case, it looks like the note was repeated; `<note>` was commented out, but the `<ab type="apparatus">` wasn't.

**Comment by wujastyk** [comment]
Aah, I see.

**Comment by ppasedach** [comment]
Sorry for that, should have looked at the file a bit more carefully before alarming you!
