### ISSUE TITLE
code documentation

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#5]
Last week I became aware of the demise of The Woolner Project database, a PHP database project at U. Vienna.  I wrote [the website](https://www.istb.univie.ac.at/woolner/), that still exists, but the [actual database](https://www.istb.univie.ac.at/cgi-bin/smwc/smwc.cgi) has been archived off by a UniVie IT staffer, apparently without notice or redress.  This is a disaster for the project, and deletes the work of many researchers over several years.  The PHP code written by Himal Trikha for the Woolner project was never documented.  It was quite extensive and, I think, tangled, and would have been extremely difficult for another person to understand or maintain. Maybe this contributed to the IT decision?

This has prompted me to think hard about the long-term support of the projects I'm involved in.  Wrt Saktumiva, it's great that it is OA and at Github.  There's one respect, though, in which I think Saktumiva could be made more future-proof, and that is code documentation.

I see that Saktumiva is a combination of Dokuwiki code written by others and new CSS, js and PHP.  For those parts of the project that you authored, Charles, would it be possible for you to drop in some short comments here and there to act as signposts for what you did and why?  My imaginary reader is a coder in a decade or two who may need to work with your system.  It needn't be a burden, just a sentence here and there to point the way.   [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) has good ideas about minimalism and purpose, I think (though we're not necessarily talking about a changelog).

Just a suggestion.
Thanks!

**Comment by chchch** [comment]
Yeah, I'm trying to clean up the code as I update things; I actually end up re-using and/or re-writing the css and javascript for other projects (like TST) and it gets a bit better with each iteration. I'll try to document it as I backport the changes.

The PHP is a another story though... it's kind of ugly. In principle it's not complicated, but there are a lot of little details that make the output just that much more refined. For the [https://github.com/chchch/sanskrit-alignment](helayo) project, I just ended up starting over in Haskell, which was a breath of fresh air. That project does something a bit different, though.

Going forward, it probably makes sense to try to split up the PHP stuff into smaller, reusable components and separate files, and do incremental rewrites/cleanups that way. I'm not really a fan of PHP, and it does seem strange to do text alignment in PHP, but it still seems to be the easiest way to code up and deploy an online project like this.

**Comment by wujastyk** [comment]
Thank you _very_ much, Charles, for attending to this.
