### ISSUE TITLE
numerical order of the witnesses

### ISSUE THREAD

**Issue by chakrabortydeepro** [chchch/upama#57]
@chchch Is there any way to fix the numerical order of the witnesses here?
![image](https://github.com/chchch/upama/assets/34675461/b0738caa-d6b9-4d9c-b89f-3c3f8bf575d5)

I wish to have it by their numerical sequence. But as the names of the witness S₂ and S₃ contains numbers 836.1 and 947, which, although smaller than the numbers of other witnesses, start with bigger numbers like 8 and 9 they are pushed after witnesses S₅ and so on. 

The same happens here:
![image](https://github.com/chchch/upama/assets/34675461/f51e3afb-72e8-420a-a696-e3b066911a59)

**Comment by chchch** [comment]
Hi,

The ordering is based on the filenames — I usually name the files 01-xxx, 02-xxx, etc. to put them in the order that I want.

**Comment by chakrabortydeepro** [comment]
Ah! My bad! Thanks, Charles. I should have realized it before.
