### ISSUE TITLE
a certain collation won't go

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#58]
When I try to collate 

- https://saktumiva.org/wiki/wujastyk/susrutasamhita/01-su.su-32-end/01-su-vulgate-edition-32-end
against
- https://saktumiva.org/wiki/wujastyk/susrutasamhita/01-su.su-32-end/provisional-edition_sutrasthana-32-end

Like [this](https://saktumiva.org/wiki/wujastyk/susrutasamhita/01-su.su-32-end/01-su-vulgate-edition-32-end), I get this error.  I can't track down the reason:

![image](https://github.com/chchch/upama/assets/762246/15cce725-28a8-4c97-95c5-ccfd2dbe90a1)

**Comment by chchch** [comment]
Looking at the pagesource for the provisional edition, it looks like there might be some non-printing character at the beginning of the file (see the red dot below):
![image](https://github.com/chchch/upama/assets/1082192/247c89ce-6e0b-48c9-8f79-f2cb400cc20e)

**Comment by wujastyk** [comment]
I found and fixed those spurious chars before <TEI.  Weird - they didn't show up in any of my usual editors, and I had to use tweak, a hex editor, to see and delete them.

Unfortunately, though, the problem persists.

**Comment by wujastyk** [comment]
I've merged the listwits , but still not quite solved.

https://github.com/chchch/upama/assets/762246/54708dd3-efd8-459a-80da-56458339444e

**Comment by chchch** [comment]
It looks like there's still two... this line:
```xml
 <listWit>
                    <witness xml:id="MN">The <title>Mādhavanidāna</title>, <abbr type="siglum"
                            >MN</abbr>
                        <idno type="siglum">Mādhavanidāna</idno></witness>
                </listWit>

                <listWit>
                    <witness xml:id="NAK_1-1146">MS Kathmandu NAK 1-1146 <abbr type="siglum"
                            >1-1146</abbr>
                        <idno type="siglum">MS NAK 1-1146</idno> A paper manuscript in Devanāgarī.
                        67 ff. Filmed as reel no A 224-9. Covers 1.8.3 - 1.44.24 of the Sūtrasthāna.
                    </witness>
                </listWit>
```
should be:
```xml
                 <listWit>
                    <witness xml:id="MN">The <title>Mādhavanidāna</title>, <abbr type="siglum"
                            >MN</abbr>
                        <idno type="siglum">Mādhavanidāna</idno></witness>
                    <witness xml:id="NAK_1-1146">MS Kathmandu NAK 1-1146 <abbr type="siglum"
                            >1-1146</abbr>
                        <idno type="siglum">MS NAK 1-1146</idno> A paper manuscript in Devanāgarī.
                        67 ff. Filmed as reel no A 224-9. Covers 1.8.3 - 1.44.24 of the Sūtrasthāna.
                    </witness>
                </listWit>
```

**Comment by wujastyk** [comment]
Drat, I was editing the wrong file (1-31, not 32-end, as I should have).  Fixed and fine now.  Apologies for messing up.
