### ISSUE TITLE
Less than/greater than symbols break in LaTeX export

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#65]
```
<lg type="verse" xml:id="HV_03_50">
<l>sphuritaśakraśarāsanahāriṇā kalayatā &lt;caturaṅgabalaśriyam&gt;/&lt;caturaṃ gavalaśriyam&gt; |</l>
<l>ka iva te 'nukṛtorjitabhūbhṛtā ghanacayena ca ye na vaśīkṛtāḥ || 50 ||</l>
</lg>
```

gets rendered okay in the web display, but in the LaTeX export the text in angle brackets disappears:

```
\setstanzaindents{2,2,2,2,2}
\stanza[\smallskip]

\large sphuritaśakraśarāsanahāriṇā kalayatā / | &
\large ka iva te 'nukṛtorjitabhūbhṛtā ghanacayena ca ye na vaśīkṛtāḥ || 50 || \&

```

**Comment by chchch** [comment]
Are you giving two different possible readings? Maybe encode it as 
```xml
<choice><seg>caturaṅgabalaśriyam</seg><seg>caturaṃ gavalaśriyam</seg></choice>
```
and then we can render that in LaTeX as `<caturaṅgabalaśriyam/caturaṃ gavalaśriyam>` or something.

**Comment by ppasedach** [comment]
Yes, I want to show that the text can be read in two way, and in order to do that you have to assume identity of v and b, but in modern orthography the words would be spelled differently. `<choice><seg>` is a good possibility. Currently, if I do that, it displays both readings one after the other without setting them apart from the surrounding text. I'd like them to render as `<reading a>/<reading b>`, which I believe is a common convention for that.

**Comment by chchch** [comment]
ok I pushed an update

**Comment by chchch** [comment]
I don't think so... I just tried `<choice><seg>viśeṣaṇa</seg><seg>viśeṣya</seg></choice>` and got `<viśeṣaṇa/viśeṣya>`

**Comment by ppasedach** [comment]
Seems to have been a browser cache issue, that the css file is still in the cache. I'll find a way to flush it. Loading the page in a different browser it is displayed correctly. The LaTeX-generated pdf also works. Just that I was thinking of `<A>/<B>` not `<A/B>`, anyway, I can live with both. Actually I would use these alternative normally in translations, where the śleṣa might otherwise not easily be identifiable. But in a case like this one, `<caturaṅgabalaśriyam>/<caturaṃ gavalaśriyam>` where you have different word separations, and have to read ba and va differently in standardized orthography it makes sense to have them in the Sanskrit text as well. In the translations, I have taken over the convention of David Smith from his Haravijaya book, but looking at it again, he seems to use single guillemets rather than smaller than/greater than symbols. There are many ways to encode texts that can be read in two ways. Probably this is just a matter of personal taste, but maybe it could also be a good idea to bring the matter to `indic-texts@lists.tei.org` to decide on some standard.

**Comment by chchch** [comment]
OK done, that's easier

**Comment by ppasedach** [comment]
Great! And reloading including CSS is <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>r</kbd>. Only in the LaTeX output it does not work now, see this image:

![Screenshot from 2023-11-14 04-25-29](https://github.com/chchch/upama/assets/11517856/fb942580-cb81-43e2-862f-98fa1fd9f6bd)

So the slash and the smaller than/greater than around the second alternative were lost.

**Comment by ppasedach** [comment]
For some reason, the smaller than-/greater than-symbols and the slash disappeared both in the online edition as well as in the LaTeX output.

**Comment by ppasedach** [comment]
Got it to work now. Had not updated my new main server to the latest version of Upama. Sorry for the noise!
