### ISSUE TITLE
Direct download link for .tex file

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#68]
Is there a way to directly download a .tex file from the server, using wget and a URL, without having to, after rsyncing new files to the server, having to switch to the browser, reload the page from there and select the LaTeX export? That would help in streamlining my workflow.

**Comment by chchch** [comment]
try `wget --content-disposition '[url]&do=export_latex'`

For example, `wget --content-disposition 'https://saktumiva.org/wiki/dravyasamuddesa/00-edition?upama_ver=fft64qrkvq&do=export_latex'`
