### ISSUE TITLE
spaces between highlighted words sometimes disappear in the LaTeX export

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#69]
This is not always the case. 

`<hi>dadhatīṃ śriyaṃ</hi> <hi>śaraddivasā</hi> <hi>ūhire</hi>`  gets rendered as `dadhatīṃśriyaṃ śaraddivasā ūhire`. But we want the space between dadhatīṃ and śriyaṃ.
`sarva<hi>rtubhiḥ</hi> <hi>samaṃ</hi> <hi>sevi</hi>taḥ` gets rendered as `sarvartubhiḥsamaṃsevitaḥ`.

I haven't figured out yet when it happens and when it doesn't.  A few more might help in identifying the pattern:

`<hi>pattrair</hi> <hi>latābhiś</hi>` renders as `pattrairlatābhiś` 

`<hi>susthitā</hi> <unclear>śobhanam āsitā.` renders as `susthitāśobhanamāsitā`, in the .tex file ` \textbf{susthitā}\uwave{śobhanam}\uwave{āsitā.}`, thus also `<unclear>` is affected.

`<hi>mṛgadṛśo</hi> <hi>vallabhais</hi> <hi>saha</hi>` is rendered as `\textbf{mṛgadṛśo}\textbf{vallabhais}\textbf{saha}`.

I can provide many more examples. This occurs quite often.

**Comment by chchch** [comment]
In the first few examples, is it also rendering with `\textbf{}`?

**Comment by ppasedach** [comment]
Yes, I should probably have copied the tex source in the first few examples, too. Here they are:
```
\textbf{dadhatīṃ}\textbf{śriyaṃ} \edtext{\textbf{śaraddivasā}}{
  \Afootnote{śira° Jammu 495 (A); °sādadhino D\textsubscript{B}(A).}
} \edtext{\textbf{ūhire}}{
  \Afootnote{\textsc{[om]} D\textsubscript{A} D\textsubscript{B}(A); dadhino Jammu 495 (A) Ś\textsubscript{A}(A).}
```

`sarva\textbf{rtubhiḥ}\textbf{samaṃ}\textbf{sevi}taḥ.`

` \textbf{pattrair}\textbf{latābhiś} `

**Comment by chchch** [comment]
Did that help?

**Comment by chchch** [comment]
I'm currently unable to reproduce the effect on my files... could you send some sample xml files?

**Comment by ppasedach** [comment]
[hv-03-p.txt](https://github.com/chchch/upama/files/13365487/hv-03-p.txt)
[test.pdf](https://github.com/chchch/upama/files/13365496/test.pdf)

Apparently github doesn't allow me to upload a file ending in `.tex` for whatever reason.

**Comment by chchch** [comment]
It actually renders ok on my server... maybe try updating some files?

**Comment by ppasedach** [comment]
It seems to be a php version related problem with an old version of php on my server.
