### ISSUE TITLE
Adding Special Characters

### ISSUE THREAD

**Issue by chakrabortydeepro** [chchch/upama#70]
A symbol (௳) called _piḷḷaiyār cuḻi_ or _Gaṇeśa Pratīka_ are used in many Grantha manuscripts. [Here](https://www.compart.com/en/unicode/U+0BF3#UNC_DB) is the Unicode character for this, where it is named as Tamil Day Sign. Could this be added to Saktumiva's special character list as `<g ref="#tamil-day-sign"/>`?

Here are some examples:

1. Both sides of om (Hamburg Cod. Palmblatt 0003_8_133)
![image](https://github.com/chchch/upama/assets/34675461/ce439aba-3d17-490d-90b1-be30a6533e51)
2. After vyākhyāsyāmaḥ (PUL Woolner 7082)
![image](https://github.com/chchch/upama/assets/34675461/c591f209-06ba-4f64-ab29-8f901a208603)
3. After pariharati (SVU ORI 3525)
![image](https://github.com/chchch/upama/assets/34675461/225f5869-f744-457c-ae95-1001f38058be)

**Comment by chchch** [comment]
I've copied over three definitions from the TST project — `#pcs` for the short _piḷḷaiyār cūḻi_, `#pcl` for the long one, and `#teti` for the same character, but used to represent the word _tēti_ in colophons. It's basically the same character, but at TST we wanted to distinguish those different usages (e.g., the three examples you show would be `#pcl` which seems to be used as punctuation, whereas `#teti` is an abbreviation, like the _mācam_ and _varuṣam_ signs for month and day. See here:

https://tst-project.github.io/editor/entities.html

See also this list of colophons; where the _piḷḷaiyār cūḻi_ is used to mean _tēti_, it appears as `{tēti}` in transliteration and as ௳ in Tamil script.

**Comment by chchch** [comment]
Oops, here's the list of colophons:

https://tst-project.github.io/paratexts/colophons/

**Comment by chakrabortydeepro** [comment]
This is great! Thank you very much, Charles.
