### ISSUE TITLE
Problems trying to do FASTA->NEXUS->NEXML

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#71]
Dear Charles,
Deepro and I are trying to create a stemmatic tree of MSS for his Saktumiva edition.

1. Output FASTA - okay (file 01output.fas)
2. mafft - apparently okay (file 02output-aligned.fas
3. fasta_to_nexus.py - I think it's giving us a wrong output (03output.nex)
4. start SplitsTree6 - it won't load the 03output.nex file.

I have two little bash files that do the needful, step1 and step2.

All the files mentioned above are in the zip file below.

[FASTA.zip](https://github.com/chchch/upama/files/13506610/FASTA.zip)

**Comment by wujastyk** [comment]
I'm getting an error message from fasta_to_nexus.py:
```
 ./fasta_to_nexus.py 02output-aligned.fas 03output.nex
Traceback (most recent call last):
  File "/home/dom/Dropbox/Xdrive/projects/Rasendramangala/splitstree/ch4-srisaila/./fasta_to_nexus.py", line 40, in <module>
    taxlabels.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

Python script attached below

[fasta_to_nexus.py.zip](https://github.com/chchch/upama/files/13968122/fasta_to_nexus.py.zip)

**Comment by chchch** [comment]
I got it to open in SplitsTree after I changed "M 1" to "M1"... it seems your sigla has a space in it?

**Comment by wujastyk** [comment]
Just a note: I've had success in generating a new tree for my Rasendramangala manuscripts. I thought Deepro and I had fixed the "M 1" issue (which we noticed) before one of our tests, but apparently not.
