### ISSUE TITLE
NEWA SIDDHI)

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#82]
Dear Charles, 

Deepro recently suggested this:

![336556244-dc308a1d-48eb-459a-9a83-ffae810f6d75](https://github.com/chchch/upama/assets/762246/d1af3a15-5102-48d2-9e12-ab40ebcc26d5)

This symbol, [at the beginning of K](https://saktumiva.org/wiki/wujastyk/susrutasamhita/01-su.su-1-31/nak_5-333_sutrasthana-1-31), appears to be Newa Siddhi sign (1144A 𑑊 NEWA SIDDHI).

Could you add this symbol to Saktumiva's repertoire, perhaps as  `<g ref="#newa-siddhi"/>`?

**Comment by chchch** [comment]
This is already implemented, I think!

**Comment by wujastyk** [comment]
Ah, good.  However, the character doesn't actually show up:

Input
![image](https://github.com/chchch/upama/assets/762246/684ea8f2-b3c9-4b8d-865e-53e3ecd864e2)

Output
![image](https://github.com/chchch/upama/assets/762246/e6d34a83-ea0c-4cb8-9e2e-a188172e618b)

I have the `<g>` filter switched to include.

**Comment by chchch** [comment]
Seems to be a bug with rendering `<g>`... should be fixed now!

**Comment by wujastyk** [comment]
All good.  Thank you!!!
