### ISSUE TITLE
missing text inside a <l>

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#86]
Is there a way to tag a stretch of text that's part of a line group as being not a _gap_ but _missing_?

I've got a line like this:

![image](https://github.com/user-attachments/assets/f69e0e1e-0f00-4bc0-87db-0069c0d7fb45)

```
  <l xml:id="SS.1.1.10"><pb n="2r" facs="002r IMG_0111.JPG"/><lb n="1"/><damage
                            type="char" n="29"><unclear>śalyajñānam upadiśatu bhagavān iti
                            </unclear></damage>
                    </l>
```

The apparatus looks like this:
![image](https://github.com/user-attachments/assets/78e0f5bd-26db-4a0d-b83a-6554276ec135)
It's the K: [om] that's worrying me (ta ūcur ... eva).  It isn't quite right to say that K _omitted_ that passage.  We don't know whether it had it or not.  We just can't read the source there.  I think it would be more accurate to say that the source is not present for that string.  So, I'd like  to be able to use that "not present" symbol,  
![image](https://github.com/user-attachments/assets/4bef1f04-06a9-4b7c-b0c3-05fefed1b671)
just for the one string or segment, not for the whole `<l>`.  Is that possible?

**Comment by chchch** [comment]
Hmm I haven't added the `<damage>` tag to the list yet... how does it display? Maybe I can add it to the list of XML tags, and then you can set it to `include` in the sidebar.

**Comment by wujastyk** [comment]
As far as I can see it doesn't do anything to the display. See [here](http://localhost/dokuwiki/doku.php?id=susrutaproject%3A01sutra1%3Akl_699_sutrasthana-1-31&upama_scroll=SS.1.1.10), where the input is 

```
      <l xml:id="SS.1.1.10"><pb n="2r" facs="002r IMG_0111.JPG"/><lb n="1"/><damage
                            type="char" n="29"><unclear reason="damaged">śalyajñānam<add place="bottom margin"
                                    resp="later scribe">+m alaṃkṛ+</add> upadiśatu bhagavān iti
                            </unclear></damage>
                    </l>
```

**Comment by wujastyk** [comment]
> Hmm I haven't added the `<damage>` tag to the list yet... how does it display? Maybe I can add it to the list of XML tags, and then you can set it to `include` in the sidebar.

... with something signifying "unavailable" rather than "omit" in the apparatus?

**Comment by chchch** [comment]
Ok I added `<damage>`, which currently looks like `<gap>` but with a different tooltip. If you want it to show up in the apparatus, it should work if you set `<damage>` to `include` in the sidebar settings.

**Comment by wujastyk** [comment]
Thank you, this is great.
