### ISSUE TITLE
<abbr> and <expan>

### ISSUE THREAD

**Issue by wujastyk** [chchch/upama#9]
Summary of earlier conversation:

>  Dear Charles, our MSS have occasional abbreviations, e.g., vyā for vyākhyāsyāmaḥ, and bha for bhavanti cātra. 
> 
> I'd like to say
> 
>     <choice><abbr type="suspension">vyā</abbr><expan>vyākhyāsyāmaḥ</expan></choice>
> 
> in accordance with https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-abbr.html.
> 
> If you agree that this is the right way to express this abbreviation, could Saktumiva be made to recognize the <expan> when collating?  At the moment, we get this:
> 
> image.png
> It would be good to see this in the apparatus not as a variant, but still to be able to see that there was an abbreviation.  I'm not sure about the best way to display this.
> 

reply:

> Hi Dominik,
> 
> I've added <expan> and <abbr> to the list of tags in the "XML tags" menu in the collation options. The default options will ignore the abbreviation and collating the expansion. You can switch it around by setting <abbr> to "Ignore tags only" and <expan> to "Ignore all". I can change the default behaviour; not sure what would be most convenient.
> 
> At the moment I've styled <abbr> and <expan> in the same way that <sic> and <corr> are styled, but we can change that at any time.

reply:

> With the input line:
> 
> 
>     <l xml:id="SS.5.1.1">athāto nnapānarakṣākalpaṃ <choice>
>     <abbr type="suspension">vyā</abbr>
>     <expan>vyākhyāsyāmaḥ</expan></choice> ||</l>
> 
> I get 90% expected, but highlighting vyā gives the wrong highlighting in the edition text on the left:
> 
> ![Screenshot from 2021-07-12 21-31-15](https://user-images.githubusercontent.com/762246/125521733-4bde53f4-3a2e-4851-9957-d5d94f7d6bbd.png)
> 

Reply:

> Hmm, what's the url of that page? Maybe remove the space between the <abbr> and <expan> tags? Actually, it looks like it might make more sense to do something like:
> 
>     vyā<ex>khyāsyāmaḥ</ex>
> 
> or even
> 
>     vyā<supplied>khyāsyāmaḥ</supplied>
> 
>

**Comment by wujastyk** [comment]
The URL is  [here](https://saktumiva.org/wiki/wujastyk/susrutasamhita/05-su.ka/provisional-edition_kalpasthana?upama_ver=gs86v0mkdq)

I think `<ex>` is a good idea.  The example in the [docs](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-ex.html), though, still has it nested inside `<expan>`.  Still, it's legal in ordinary paragraphs and lines, so hey.

I'm less keen on `<supplied>` because it doesn't convey the scribe's intention to abbreviate.  It's more for damage and illegibility.

**Comment by chchch** [comment]
So I fixed an XSLT bug so that the `<abbr></abbr><expan></expan>` pattern should work as expected now. I also added `<ex>` to the list of XML tags, so that you can try `<expan><ex></ex></expan>`. I think that might be closer to what you're looking for; you can switch `<ex>` between "Ignore all" and "Ignore tags only".

**Comment by wujastyk** [comment]
thank you, Charles.  I'll test it later today or tomorrow.  Great stuff.
Yesterday, playing with this tagging, I realized that I didn't have a clear
idea in my mind about what I thought it should look like in the apparatus,
ideally.  My main starting point was that if vyā were tagged as an
abbreviation for vyākhyāsyāmaḥ then it shouldn't collate as a variant
reading.  But quite how to display all that in the apparatus, to a reader,
still isn't quite obvious to me.

**Comment by chchch** [comment]
Ah ok, I think for that it would make sense to write `<expan>vyā<ex>khyāsyāmaḥ</ex></expan>`, then:
* set `<expan>` to "Ignore tags only", and 
* set `<ex>` to "Ignore tags only". 

Then it will just collate as if it said `vyākhyāsyāmaḥ`.

**Comment by wujastyk** [comment]
thanks!

**Comment by wujastyk** [comment]
This looks excellent to me:
[image: Screenshot from 2021-07-12 21-31-15.png]

This was the input:

  <l xml:id="SS.5.1.1">athāto nnapānarakṣākalpaṃ
                <choice><abbr
type="suspension">vyā</abbr><expan><ex>khyāsyāmaḥ</ex></expan></choice>
||</l>
